version: '2'
services:
    mathfineco-app:
        image: mathfineco
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mathfineco-mysql:3306/mathfineco?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=mathfineco-elasticsearch:9300
        ports:
            - 8080:8080
    mathfineco-mysql:
        extends:
            file: mysql.yml
            service: mathfineco-mysql
    mathfineco-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: mathfineco-elasticsearch
